//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace olah_nilai
{
    using System;
    using System.Collections.Generic;
    
    public partial class siswa
    {
        public int id { get; set; }
        public Nullable<int> nisn { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string kelamin { get; set; }
        public string lahir { get; set; }
        public System.DateTime tgl { get; set; }
        public string kelas { get; set; }
    }
}
